DROP TYPE IF EXISTS article_category;
CREATE TYPE article_category AS ENUM (
     'Listicle',
    'How-to',
    'News',
    'Interview',
    'Story'
);

CREATE TABLE blogful_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    style article_category NOT NULL,
    content TEXT,
    date_published TIMESTAMP DEFAULT now() NOT NULL
    
);
