-- CREATE TABLE blogful_articles (
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     title TEXT NOT NULL,
--     content TEXT,
--     date_published TIMESTAMP DEFAULT now() NOT NULL
-- );

-- CREATE TYPE article_category AS ENUM (
--     'Listicle',
--     'How-to',
--     'News',
--     'Interview',
--     'Story'
-- );

-- ALTER TABLE blogful_articles
--   ADD COLUMN
--     style article_category;

-- CREATE TABLE blogful_users (
--   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--   fullname TEXT NOT NULL,
--   username TEXT NOT NULL UNIQUE,
--   password TEXT,
--   nickname TEXT,
--   date_created TIMESTAMP NOT NULL DEFAULT now()
-- );

-- ALTER TABLE blogful_articles
--   ADD COLUMN
--     author INTEGER REFERENCES blogful_users(id)
--     ON DELETE SET NULL;


-- thsi is version 4
CREATE TABLE blogful_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    text TEXT NOT NULL,
    date_commented TIMESTAMP DEFAULT now() NOT NULL,
    article_id INTEGER
        REFERENCES blogful_articles(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES blogful_users(id) ON DELETE CASCADE NOT NULL
);